namespace: skydive
name: skydive
version: 0.1.0
readme: README.md
authors: null
description: null
license: GPL-3.0-or-later
license_file: COPYING
tags: null
dependencies: {}
repository: git@github.com:coll-test/skydive.skydive.git
documentation: https://github.com/coll-test/skydive.skydive/tree/master/docs
homepage: https://github.com/coll-test/skydive.skydive
issues: https://github.com/coll-test/skydive.skydive/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
